"""create index_price

Revision ID: 79ae52210a7f
Revises: 
Create Date: 2026-01-29 01:00:14.769663

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

import sqlmodel 

# revision identifiers, used by Alembic.
revision: str = '79ae52210a7f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('indexprice',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('index_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('index_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('timestamp', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('indexprice', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_indexprice_index_name'), ['index_name'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('indexprice', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_indexprice_index_name'))

    op.drop_table('indexprice')
    # ### end Alembic commands ###
